import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Hansol Mini Projects',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}

export function Footer() {
  return (
    <footer className="mt-12 bg-gray-800 py-8 text-gray-400">
      <div className="container mx-auto px-4 text-center">
        <div className="mb-2 space-x-4">
          {/* 1. 개인정보처리방침 */}
          <Link href="/privacy" className="hover:text-white">
            개인정보처리방침
          </Link>
          <span>|</span>
          {/* 2. 이용약관 */}
          <Link href="/terms" className="hover:text-white">
            이용약관
          </Link>
        </div>
        {/* 3. 저작권 */}
        <p className="text-sm">
          © {new Date().getFullYear()} Hansol's Mini Projects. All rights
          reserved.
        </p>
      </div>
    </footer>
  );
}